# Generated by Django 5.0.4 on 2024-04-17 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_authuser_tipo_usuario_alter_tipousuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='tipo_usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_usuario', to='application.tipousuario'),
        ),
    ]
