# Generated by Django 5.0.4 on 2024-04-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_authuser_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='tipo_usuario',
            new_name='id_tipo_usuario',
        ),
    ]
